version: "3.9"
services:
  backend:
    build: .
    expose:
      - 8000
    command: >
      bash -c "python manage.py makemigrations && 
      python manage.py migrate --noinput && 
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 4"

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
